feat: create keycloak token verification
jabardigitalservice/digiteam-inventaris-service pull request #2
Opened 2022-09-21 09:01 UTC by iqbal167

# Overview
- feat: membuat midleware (keycloak token verification) 

## Link / Related Issue
- Berhubung middleware untuk verifiikasi token ini merupakan feature penting yang harus ada sebelum fitur pada module-module lainnya.

## Todo
- Membuat API permohan barang

## Evidence
- Title: feat: create keycloak token verification
- Project: Digiteam Inventaris Platform
- Participants: @iqbal167

2022-09-21 13:18 UTC, liondy requested changes
i think .env.example gaperlu ditampilin
update di wiki aja kali ya

2022-09-21 13:20 UTC, liondy commented
Halo @iqbal167 next time create branch nya task/#no-card dan pull-request ke `feature/sprint-1` ya, nanti di akhir sprint baru di merge ke branch `development`

2022-09-22 01:57 UTC, ayocodingit commented on .env.example
> +MYSQL_DATABASE=
kang @iqbal167, minor ya lebih baik ditambahkan baris baru pada akhir file untuk semua file

2022-09-22 01:57 UTC, ayocodingit commented on src/common/exceptions/http-error.filter.ts
> +    // const request = ctx.getRequest<Request>();
ini boleh di remove aja dulu yah kang, jika belum terpakai 😄

2022-09-22 02:13 UTC, iqbal167 commented on .env.example
> +MYSQL_DATABASE=
jadi tinggal kasih enter aja gitu ya kang?

2022-09-22 02:18 UTC, ayocodingit commented on .env.example
> +MYSQL_DATABASE=
iya betul kang 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41193120/191643833-a63a8ddb-fdbf-430a-bf36-a02a90cffc29.png">

2022-09-22 02:34 UTC, iqbal167 commented on src/common/exceptions/http-error.filter.ts
> +    // const request = ctx.getRequest<Request>();
kang @ayocodingit udah diperbaiki di [91ad8b0](https://github.com/jabardigitalservice/digiteam-inventaris-service/pull/2/commits/91ad8b062e16e5b2678079c06d7e55f96a19abd0)

2022-09-22 02:35 UTC, ayocodingit approved these changes

2022-09-22 02:51 UTC, rindibudiaramdhan approved these changes
mau tanya, kalau samples ini di TS digunakan untuk apa ya?
Unit Test ya?

2022-09-22 03:33 UTC, iqbal167 commented
> mau tanya, kalau samples ini di TS digunakan untuk apa ya? Unit Test ya?

2022-09-22 03:36 UTC, iqbal167 commented
> mau tanya, kalau samples ini di TS digunakan untuk apa ya? Unit Test ya?

bukan kang, ikut saya buat sendiri. untuk test endpint saja

2022-09-22 03:44 UTC, merged